baseURL: "https://filmlabdb.github.io/"
languageCode: "en-gb"
title: "filmlabDB"

params:
  mainSections: labs

menu:
  main:
    - identifier: about
      name: About
      title: About
      url: /about/
      weight: 0

    - identifier: map
      name: Map
      url: /map/
      weight: 1

outputs:
  home:
    - html
    - json

googleAnalytics: UA-160189334-2
privacy:
  googleAnalytics:
    anonymizeIP: true
    respectDoNotTrack: true
    useSessionStorage: true
